SELECT * FROM ORDERS;
SELECT * FROM TEST;

SELECT FirstName FROM TEST, ORDERS WHERE TEST.ID = ORDERS.ID; 

SELECT FirstName from TEST NATURAL JOIN ORDERS;

SELECT A.AGE, B.FIRSTNAME AS HIGHER_AGE, A.FIRSTNAME AS LOWER_AGE

FROM TEST AS A, TEST AS B
WHERE A.AGE < B.AGE;
